services:
  server:
    # image: build_analytic_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:   
      - 8003:8003
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yml

  db_service:
    image: timescale/timescaledb:latest-pg15 
    environment:
      - POSTGRES_USER=timeuser
      - POSTGRES_PASSWORD=pass33
      - POSTGRES_DB=timescaledb
    ports:   
      - "127.0.0.1:5432:5432" 
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "timeuser"]
      interval: 10s
      timeout: 5s
      retries: 5 
      start_period: 15s


volumes:
  timescaledb_data: