services:
  server:
    image: build_analytic_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8003
    env_file:
      - .env.compose
    ports: 
      - 8003:8003
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yml
    depends_on:
      - db_service
  db_service:
    image: timescale/timescaledb:latest-pg15 
    environment:
      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-password
      - POSTGRES_DB=timescale
    ports: 
      - 4000:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data


volumes:
  timescaledb_data: